### PR TITLE
Fix crreate note on the same spot

### LINKED ISSUE #71: Check if note is in the slot when creating one
Now backend doesn't check if there is a note in the position sent from client, because server relies on client here. So now it is possible to create multiple notes on the same spot if users send create requests simultaneously and  don't receive updates in time. 
Expected behavior is to send bad request if user tries to add a note on the free (but taken) slot.

### PR DESCRIPTION
**Pull request by PaulKovalov**
* Fixes the bug when > 1 users create a note in the same cell, closes #71

### CODE REVIEW

File: sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NoteServlet.java [hunk 1]
```diff
@@ -51,15 +51,23 @@ protected void doPost(HttpServletRequest request, HttpServletResponse response)
...
+    // get the board of the note
+    // check that the position of note doesn't clash with the position of other notes
+    Whiteboard board = ofy().load().type(Whiteboard.class).id(note.boardId).now();
+    for (Ref<Note> noteRef: board.notes) {
+      Note existingNote = noteRef.get();
+      if (existingNote.x == note.x && existingNote.y == note.y) {
+        badRequest("Coordinates already taken", response);
+        return;
+      }
+    }
```
Comment (AndrzejPodo) [inline sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NoteServlet.java:63]: Good to have such validation here, but the bug originates from the front-end, right? We have also some bug in our "find closest position" algorithm that allows placing note at already taken position in some circumstances.

**Review by AndrzejPodo — APPROVED** [review]

File: sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NoteServlet.java (hunk 1 above)
Comment (PaulKovalov) [reply sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NoteServlet.java:63]: It fixes the bug when user have not received an update, but in fact the note is in that slot already. It is not a bug actually, it is a feature  :P. An example of when this check is required: two users try to create a note in the same cell simultaneously, because they are not synced in real time, without this check two notes will appear in the same slot. 
"find closes position" is something other, it is not related to this PR

Comment (PaulKovalov) [reply sticknotesbackend/src/main/java/com/google/sticknotesbackend/servlets/NoteServlet.java:63]: it is not frontend bug
